#!/bin/bash
# vim-phptags.sh
# 当前脚本用来生成 GTAGS 库，请按具体需求修改以下 find 命令中的参数
#
# 使用非当前目录的 GTAGS 库，需要定义 $GTAGSLIBPATH 环境变量
# $GTAGSLIBPATH 为 GTAGS 所在的目录
# export GTAGSLIBPATH=/path/to/common/gtags
#
# 使用：
# 仅对当前目下的 php 文件生成 tags：
# $ vim-phptags
# 如果目录下的软链也需要生成 tags，需要主动作为参数传入，如这里的 Soli：
# $ vim-phptags . ./Soli/
#

if [ ! -n "$1" ] ;then
    DIR="."
else
    DIR="$@"
fi

TAGS_FILE=gtags.files

# 1. 查询 .php 后缀文件
# 2. 排除不需要生成 tags 的目录
# 3. 使用 sed 将软链目录后的双斜杆替换为单斜杆
find $DIR -type f -name "*.php" \
    ! -path "./cache/*" ! -path "./vendor/*" \
    | sed 's@//@/@' > $TAGS_FILE

gtags

#cscope -bkq -i $TAGS_FILE
#ctags -L $TAGS_FILE -f tags
#rm -f $TAGS_FILE
